- results/package.json
- results/src/core/helpers/pageContext.js
- results/src/core/helpers/pageContext.tsx
- results/src/core/i18n/i18nContext.tsx
- results/src/core/i18n/translator.ts
- results/yarn.lock
This is a pretty loose first attempt at typing the i18n system. More work needs to be done to enable strong typing here. 
Specifically, we need to initialize the application with a default locale (or interface-compatible placeholder) so that we can guarantee that there will always be translation functions available in the I18nContext Provider.
> First pass at typing i18n files

- results/src/core/blocks/block/BlockTabs.js
> less margin below page title on mobile sizes

- results/src/core/components/sidebar/Nav.js
- results/src/core/components/sidebar/Sidebar.js
- results/src/core/layout/MainLayout.js
- results/src/core/pages/PageFooter.js
- results/src/core/pages/PageTemplate.js
> feat: set up landmark structure for site

- results/src/core/blocks/block/BlockVariant.js
> feat: top align SideArea on mobile

- results/src/core/blocks/block/BlockChart.js
- results/src/core/blocks/features/FeatureExperienceBlock.js
Removes the copious H4s (makes it difficult to navigate via headings) and replace it with the semantically more correct dt/dd.
> feat: change stacked bar charts into DLs for semantics

- results/src/core/blocks/block/BlockData.js
> feat: spacing around export buttons

- results/src/@types/styled.d.ts
- results/src/core/blocks/block/BlockDebug.tsx
- results/src/core/blocks/block/BlockVariant.tsx
- results/src/core/blocks/generic/VerticalBarBlock.tsx
- results/src/core/helpers/pageContext.tsx
- results/src/core/types/block.ts
I've made a start on moving some bits over to TS.
> refactor: :label: first stab at adding types

- results/src/core/components/Head.js
It's hardcoded, I couldn't figure out how to get it from the survey theme.
> feat: add theme color

- results/src/core/icons/IconWrapper.js
appearance: button on the tabs caused the issue.
> feat: fix buttons on safari

- results/src/core/components/Popover.js
| ![image](https://user-images.githubusercontent.com/4408379/145993830-ddd96209-87ad-4180-9e0f-f5d5c9be3999.png) | ![image](https://user-images.githubusercontent.com/4408379/145993786-f955333a-03dc-44cd-8d7c-0592284092c2.png) |
cc @SachaG
> Remove width limit from popover

- results/src/core/helpers/stripHtml.js
- results/src/core/share/SharePreview.js
| ![image](https://user-images.githubusercontent.com/4408379/145995264-ab5542fb-42c5-439b-842a-1d7fa93b3f0f.png) | ![image](https://user-images.githubusercontent.com/4408379/145997346-6872f745-9d60-431a-a7ed-f307b0571828.png)|
|  ![image](https://user-images.githubusercontent.com/4408379/145999081-f34d5fba-8c31-4138-bc01-89baa3af5a0a.png)| ![image](https://user-images.githubusercontent.com/4408379/145999025-c989495b-2afe-4dff-92d5-6632dc7c7dc5.png) |
> Strip paired HTML tags and Markdown in share preview

- results/src/core/components/ModalTrigger.js
| ![ezgif com-gif-maker (14)](https://user-images.githubusercontent.com/4408379/146074932-68a39cf7-7f94-4846-a639-c0b064ec12ac.gif) | ![ezgif com-gif-maker (15)](https://user-images.githubusercontent.com/4408379/146074939-102fba44-2a07-43e8-b0e2-3203c46ab6b2.gif) |
> Keep same position modal close button when focusing

- results/src/core/blocks/block/BlockLegendsItem.js
- results/src/core/charts/tools/ToolsScatterplotChart.js
I don't know how legit my fix is, but it's works.
I also vertically centered colored legend square and increased the clickable area of whole parent item slightly.
| ![ezgif com-gif-maker (17)](https://user-images.githubusercontent.com/4408379/146078593-b8ab303b-2fbd-4ed1-a663-9da342475ef8.gif) | ![ezgif com-gif-maker (18)](https://user-images.githubusercontent.com/4408379/146078609-0f663e7f-b369-4425-a334-2be816f78f42.gif) |
> Fix highlighting items when hovering category in Tools Scatterplot

- results/src/core/helpers/useBucketKeys.ts
| ![image](https://user-images.githubusercontent.com/4408379/146144563-57b3758e-45f5-4883-95ab-2fb458b740fc.png) | ![image](https://user-images.githubusercontent.com/4408379/146144445-8626caee-1e56-4f81-ac5b-47850d4e3617.png) |
> Strip HTML in bar chart

- results/src/core/blocks/other/CreditItem.js
none of the images in the list of credits had alt attributes, so that needed to be fixed.
> add alt attribute to credits

- results/src/core/blocks/tools/ToolsExperienceRankingBlock.tsx
The ranking chart had the same issue as the map, so it gets the same fix!
> add min width for ranking chart

- surveyform/src/account/user/components/LogoutButton.tsx
> Make logout button translatable

- surveyform/src/account/magicLogin/components/StandaloneMagicLoginForm.tsx
> Make email placeholder translatable

- surveyform/src/account/user/components/LogoutButton.tsx
- surveyform/src/core/components/common/Footer.tsx
> Make logout pseudo-link clickable

- surveyform/src/core/components/forms/Checkboxgroup.tsx
cc @eric-burel @SachaG 
See and merge also https://github.com/Devographics/locale-en-US/pull/24
> Make Show More button translatable

- api-internal/src/data/locales.yml
related: https://github.com/Devographics/locale-ko-KR/pull/3
> add new translator

- api-internal/src/data/locales.yml
fix: Change incorrect Hrvatski to Indonesia
> fix: Indonesia

- README.md
Fixes Devographics/Monorepo#176
Not sure if you want outside PR's but thought I'd leave one for the simple fix.
> Typo in the README - 

- api/src/server.ts
- surveyadmin/.env.example
- surveyadmin/src/components/cache/Api.tsx
- surveyadmin/src/scripts/refreshCache.ts
- surveyadmin/src/scripts/reloadAPI.ts
- surveyform/.env.example
- surveyform/cypress/e2e/e2e/fillResponse.cy.ts
- surveyform/cypress/helpers/getters.ts
- surveyform/src/components/inputs/TextList.tsx
/!\ It doesn't work yet, it's a first attempt at cleaning the component
Edit: now it looks like it works but that's a beast, please test :pray:
@SachaG @LeaVerou 
Implements #284
> Text list 2 items

- api/src/compute/raw.ts
- api/src/generate/resolvers.ts
- api/src/graphql/templates/responses.ts
- api/src/graphql/typedefs/schema.graphql
- surveyform/src/components/common/Score.tsx
- surveyform/src/components/form/FormComment.tsx
- surveyform/src/components/form/FormItem.tsx
- surveyform/src/components/inputs/experience/Followup2.tsx
- surveyform/src/lib/responses/helpers.ts
- surveyform/src/stylesheets/_colors.scss
- surveyform/src/stylesheets/_feature_v3.scss
- surveyform/src/stylesheets/_score.scss
We don't actually need the id arrays, we can compute the counts directly, but since the previous code did that, I kept it.
> First stab at fair score

- surveyform/src/components/ui/Button.tsx
> fix: polymorphic button
