Devographics/Monorepo

results/src/core/pages/PageFooter.js
Makes sure the footer navigational buttons never have cut of contents but instead wrap.
=> feat: responsive footer navigation

results/src/core/charts/ChartContainer.js
We can further tweak the exact value later since I'd also like to move the sidebar to the top on mobile, but 500px seems fine. There's nothing wrong with scrolling horizontally there, we should just not make people scroll unnecessarily .
=> feat: force less wide ranking charts on mobile

results/src/core/blocks/block/BlockTabs.js
tabs now sit below title on smaller widths.
Tab bar itself will scroll when even narrower.
=> feat: tabs on mobile scroll horizontally

results/surveys/css2021/theme/typography.ts
This sets the minimum font size to 12px instead of 11.something. (12 really is the bare minimum)
=> feat: set minimum font size to 12px

results/src/core/blocks/features/FeatureExperienceBlock.js, results/src/core/charts/ChartContainer.js
feature experience block had an overflow issue with the tooltips caused by an explicit scroll overflow, that's been replaced with max-width.
=> fix tooltip overflow issue on small widths

results/src/core/blocks/brackets/BracketMatchupsBlock.tsx
todo: the hover tooltips now have the same background color as the page, but we probably want to change that to blue on white like the tooltips of other charts (but I couldnt quickly find where that gets set)
=> feat: better styling for bracket matchup block

results/src/core/blocks/awards/AwardBlock.js
Before:
https://2021.stateofcss.com/en-US/awards/[object%20Object]
After
https://postcss.org/
cc @SachaG
=> Fix award winner links

results/src/core/theme/GlobalStyle.ts
Since the site is done in dark tones, it probably makes sense to make the browser/native UI in the corresponding colors.
Such sharp contrast (light native UI components and dark colors throughout the site) hurts your eyes. 
Before:
After:
=> Use dark UI appearance

results/src/core/share/ShareLink.js
Then sharing icons will also be vertically aligned to the center.
| ![image](https://user-images.githubusercontent.com/4408379/145898806-654e1293-dc40-469f-b9dc-52b9d5d22ac6.png) |  ![image](https://user-images.githubusercontent.com/4408379/145898666-6db4e5e9-e364-451b-8c6b-b46a3bb91fc2.png)|
=> Make narrower Share Options block

api/src/resolvers/entities.ts
As one example - https://2021.stateofcss.com/en-us/technologies/css-in-js/
NPM link leads to https://www.npmjs.com/package/undefined
=> Fix undefined npm links

results/src/core/charts/generic/TickItem.tsx, results/src/core/components/Tooltip.js
1. Remove native title
| ![image](https://user-images.githubusercontent.com/4408379/146003902-95eee298-cec1-4d28-a2e4-e7675e4f5995.png) | ![image](https://user-images.githubusercontent.com/4408379/146003670-ff322c8f-0201-446c-b65e-ffe5713675c3.png) |
2. Make clickable only those items that have a link
| ![image](https://user-images.githubusercontent.com/4408379/146004433-1eb1cad2-4b3f-4a0c-885e-fdb5bd1b8f2c.png)| ![image](https://user-images.githubusercontent.com/4408379/146004529-99a57e5e-6cf8-42f6-b463-48c3155fa607.png) |
cc @SachaG
=> Various TickItem improvements

results/src/core/blocks/block/BlockShare.js, results/src/core/share/ShareLink.js
This issue is relevant for translations where the messages may be longer than the original ones.
| ![image](https://user-images.githubusercontent.com/4408379/146075711-6e867b15-bdce-4e94-9736-f83198204503.png) | ![image](https://user-images.githubusercontent.com/4408379/146075785-a9bd5b12-ea4c-45d5-a124-17efd344a923.png) |
=> Add small gap between sharing items in modal

results/src/core/blocks/block/BlockLinks.js
Although this is a problem in the entity data (btw, I [made the fix](https://github.com/StateOfJS/entities/pull/1) for the case shown below), it is still a good thing to handle such a case.
Before:
After:
=> Fix fatal error when invalid URL of entity

results/src/core/blocks/demographics/ParticipationByCountryBlock.js, results/src/core/charts/ChartContainer.tsx
This adds a new minWidth property to the chartContainer that the ParticipationByCountryBlock uses to make sure the full map is shown. Also includes a fix for the internal vertical scrollbar.
=> Add correct minimum width for map on mobile

results/src/core/blocks/block/sponsor_chart/SponsorCredit.tsx
This prevents the username from being read twice for both the headings and links. Because the username is already in the link, the image can have an empty alt attribute.
=> remove alt text from sponsor image due to duplication

results/src/core/components/sidebar/Nav.js
The sidebar nav links don't currently match paths with trailing slash, which is a problem because paths is the sitemap are generated with a trailing slash (not sure why: https://github.com/StateOfJS/Monorepo/blob/main/results/node_src/sitemap.js#L108). The result is that sidebar nav links don't display as active when following PaginationLinks.
=> fix nav active page to match trailing slash

surveyform/src/modules/countries.ts
Reference — https://en.wikipedia.org/wiki/Kazakhstan
=> Fix typo in Kazakhstan country name

results/src/core/blocks/other/CreditItem.js
Checking https://2022.stateofcss.com/en-US/conclusion/ on my phone I realized that Lea's avatar was being stretched.
The issue only appears if the role text is longer than 1 line.
Below screenshots with Chrome at 420px width:
**Before**
**After**
=> Fix CreditItem Avatar stretching on mobile

results/src/core/blocks/explorer/Corner.tsx
This is a quick fix,  since still header cells overlap popovers.
cc @SachaG
=> Avoid overlapping lang menu with header cells of data explorer

results/surveys/css2022/config/recommended_resources.yml
The link of the course [SVG Essentials & Animation, v2](https://frontendmasters.com/courses/svg-essentials-animation/?utm_source=stateofcss&utm_medium=website&utm_campaign=stateofcss2021&utm_content=textlink) by Sarah Drasner is redirecting to the same page.
The link of the course [SVG Essentials & Animation, v2](https://frontendmasters.com/courses/svg-essentials-animation/?utm_source=stateofcss&utm_medium=website&utm_campaign=stateofcss2021&utm_content=textlink) by Sarah Drasner is redirecting to the Frontend Masters course.
=> Fix: SVG course link

results/src/core/charts/people/PeopleBlock.tsx
The new social links don't need to be constrained even at 320px wide but they do have a 1px miscalculation (?) scroll at smaller widths. So to prevent scrollbars appearing, just let them overflow that 1px.
=> prevent creation of scrollbar for new people sociallinks

results/surveys/css2023/config/recommended_resources.yml, shared/types/outlines.ts, surveyform/.env.example, surveyform/src/app/[lang]/AppLayout.tsx, surveyform/src/app/[lang]/survey/[slug]/[year]/rsc-fetchers.ts, surveyform/src/components/form/typings.ts, surveyform/src/components/inputs/TextList.tsx, surveyform/src/components/questions/SurveySectionContents.tsx, surveyform/src/lib/customComponents.ts
See https://github.com/Devographics/surveys/discussions/185
This implement a "textlist" type of question.
This does NOT implement a "multiple + a list of others values" (= a checkbox group with known options and the possibility to add a list of other options), though the array management logic would be slightly similar.
- Namely React keys are not properly handled yet, which is visible if you add for instance 3 items but remove the second one. Each new input should be assigned a random key to be treated as an entity instead.
- Also I don't get yet know what need to be done in the API to support a new type of question. I see warnings saying "textlist" is not known so that's a starting point
- This is a draft, neither the UI/UX or the code are really correct. 
- The PR aims the "devel" …
=> "textlist" component

api/src/graphql/typedefs/schema.graphql, shared/fetch/queries/edition_metadata.ts, shared/types/outlines.ts, surveyform/src/components/inputs/Checkboxgroup.tsx, surveyform/src/components/inputs/CheckboxgroupSentiment.tsx
Haven't tested it yet, wanted to get some feedback on direction.
Note that right now it will default to the old behavior if no `order` is set, for backwards compat. Eventually we probably want the default behavior to be the specified order; I cannot think of many use cases where alphabetical sorting is actually desirable (perhaps only demographics questions like Sector etc).
Not sure if `order` is too general; maybe we want to call it `optionsOrder`?
=> First stab at `order` property to replace `randomize`, closes #293
